const strings = {
    LOGIN_HEADER: "Log-in",
    email_address: "Email ID",
    enter_password: "Enter Password",
    enter_email_address: "Enter Email ID",
    password: "Password",
    enter_text: "Enter text here",
    password_text: "Password will be a combination of Numbers, Alphabets and Characterts",
    forget_password: "Forgot Password",
    dont_have_acc: "Don't have Account?",
    sign_up: "Sign-Up",
    or_sign_in_with: "Or Sign-in with:",
    first_name: "First Name",
    last_name: "Last Name",
    phone_no: "Phone Number",
    already_have_acc: "Already Have An Account?",
    hear_about_it: "How did you hear about us?",
    facebaook: "Facebook",
    instagram: "Instagram",
    twitter: "Twitter",
    stockwits: "StockWits",
    youtube: "Youtube",
    reddit: "Reddit",
    linkedIn: "LinkedIn",
    member_referral: "Member Referral",
    others: "Others",
    source_name: "Source Name",
    submit: "Submit",
    forgot_password_content: "You can reset your password via your registered email ID.\nAn email with the instructions and link to set new password will be sent on email ID,Please check spam folder.",
    app_name: 'BlackBox Stocks',
    latest_gainers: "Latest Gainers Nowadays",
    know_more: 'Know More',
    t_and_c_applied: 'T&C applied',
    top_gainers: 'Top Gainers',
    real_time_news: 'Real Time News',
    terms_and_condition_heading: "Privacy Statement",
    temrs_and_cond_para: "THIS PRIVACY STATEMENT DISCLOSES the privacy practices for Blackbox,Inc. (the “Company”).\n \nInformation Collection and Use The Company is the sole owner of the information collected on this site. We will not sell, share or rent this information to others in ways different from what is disclosed in this statement.\n\nThe Company reserves the right to update this statement from time-to-time, but shall make any updates available to its consumers.\n\nLog Files We use IP addresses to administer the site, track user movement and gather demographic information for aggregate use. IP addresses are not linked to identifiable information.\n\nAs most website business models include the sharing of services and customer information, disclosure of these relationships is a must.\n\nSharing We will share aggregated demographic information with our partners and advertisers. This is not linked to any personal information that can identify any individual person.\n\nLinks This website contains links to other sites. We are not responsible for the privacy practices of other sites.",
    time: "TIME",
    volatility: "VOLATILITY",
    percertage_change: "%CHANGE",
    home: "Home",
    my_account: "My Account",
    settings: "SETTINGS",
    legal_term: "LEGAL TERMS",
    logout: "LOGOUT",
    arrow : '>'
}

export default strings;